choice_practice/models.py
from otree.api import (
    models,
    widgets,
    BaseConstants,
    BaseSubsession,
    BaseGroup,
    BasePlayer,
    Currency as c,
    currency_range,
)
from timeit import default_timer as timer
import numpy as np
import pandas as pd
import time

author = 'Your name here'

doc = """
Your app description
"""

def practice_generator(treatment):

    rewards = [12.3, 19.7, 8.55, 6.35, 16.6, 23.4]
    risks = [82, 58, 82, 41, 58, 41]
    certainty = [6.85, 15.67, 5.79, 1.36, 7.44, 14.11]
    display = [0, 1, 1, 1, 0, 1]

    if treatment == 'E':
        for i in range(len(rewards)):
            rewards[i] = round(rewards[i])

        for i in range(len(risks)):
            risks[i] = round(risks[i] / 10) * 10

        for i in range(len(certainty)):
            certainty[i] = round(certainty[i], 1)

    trial_list = []
    for i in range(len(rewards)):
        dum = [rewards[i], risks[i], certainty[i], display[i]]
        trial_list.append(dum)

    trial_table = pd.DataFrame(trial_list)

    columns = ['reward', 'risk', 'certainty', 'display']
    trial_table.columns = columns

    # np.random.seed(520)
    # trial_table = trial_table.sample(frac=1).reset_index(drop=True)

    return trial_table

def set_time():

    time_now = timer()

    return time_now


class Constants(BaseConstants):
    name_in_url = 'choice_practice'
    players_per_group = None
    num_rounds = 6 #should be 6


class Subsession(BaseSubsession):
    pass


class Group(BaseGroup):
    pass


class Player(BasePlayer):
    treatment = models.StringField()

    choice = models.StringField()

    # decision time collected by JavaScript method
    jsdectime_start = models.FloatField()
    jsdectime_end = models.FloatField()
    jsdectime = models.FloatField()
    # decision time collected by Python method
    pydectime = models.FloatField()

    pyresttime = models.FloatField()

    reward = models.FloatField()
    risk = models.FloatField()
    certainty = models.FloatField()
    display = models.IntegerField()

    lottery = models.IntegerField()

choice_practice/_builtin/__init__.py
# Don't change anything in this file.
from .. import models
import otree.api


class Page(otree.api.Page):
    subsession: models.Subsession
    group: models.Group
    player: models.Player


class WaitPage(otree.api.WaitPage):
    subsession: models.Subsession
    group: models.Group
    player: models.Player


class Bot(otree.api.Bot):
    subsession: models.Subsession
    group: models.Group
    player: models.Player

choice_practice/templates/choice_practice/AfterPage.html
{% extends "global/Page.html" %}
{% load otree static %}

{% block title %}
Practice Session
{% endblock %}

{% block content %}

<body>
  {% if display == 0 %}
  <!-- lottery shown on the right hand side -->
  <br>
  <section>
    <article id="option_left">

      <div class="certainty_div">
        <p class = "certainty_txt">{{ certainty }}</p>

      </div>

    </article>

    <article id="option_right">
      <div class="risk_up_div" style="height: {{ risk_up_px }};">
        <p class="risk_up_txt">{{ risk_up }}</p>
      </div>
      <div class="risk_down_div"  style="height: {{ risk_down_px }};">
        <p class="risk_down_txt">{{ risk_down }}</p>
      </div>
      <div class="reward_div">
        <p class="reward_txt">{{ reward }}</p>
      </div>

    </article>
  </section>

  {% else %}
  <!-- lottery shown on the left hand side -->
  <br>
  <section>
    <article id="option_left">
      <div class="risk_up_div" style="height: {{ risk_up_px }};">
        <p class="risk_up_txt">{{ risk_up }}</p>
      </div>
      <div class="risk_down_div"  style="height: {{ risk_down_px }};">
        <p class="risk_down_txt">{{ risk_down }}</p>
      </div>
      <div class="reward_div">
        <p class="reward_txt">{{ reward }}</p>
      </div>

    </article>

    <article id="option_right">

      <div class="certainty_div">
        <p class = "certainty_txt">{{ certainty }}</p>

      </div>

    </article>
  </section>
  {% endif %}

  <div style="font-size: 20px;">
    <br>
    <p>In this trial, you need to decide whether to trade {{certainty}} for a lottery, which has {{risk_down}} percent of chance to win {{reward}}. <br>– If you decide the lottery is more attractive, press the {{lot_key}} key to choose the lottery on the {{lot_key}}. <br>– If you decide to keep the money, press the {{tag_key}} key to choose the monetary amount on the {{tag_key}}.</p>

    <p>[This instruction will not be shown in the actual trials]</p>

  </div>


</body>

<!-- <input type="hidden" name="choice" id="id_choice" value='nothing'> -->

<!-- <center>(Press left or right arrow)</center> -->

{% endblock %}

{% block scripts %}

<script>
  // document.documentElement.style.cursor = 'none';
  // This is to hide the cursor, work the same as the CSS method.

  var choice = '{{ choice | safe }}';
  if (choice == 'left') {
    document.getElementById("option_left").style.border = "5px solid white";
  } else {
    document.getElementById("option_right").style.border = "5px solid white";
  }

</script>

{% endblock %}

{% block styles %}
<style type="text/css">

  .otree-title {
    font-size: 0;
  }

  article {
    float: left;
    width: 50%;
    background-color: black;
    padding: 20px;
    vertical-align: middle;
    height: 450px;
    box-sizing: border-box;
    border: 5px solid transparent;
  }

  /* Clear floats after the columns */
  section:after {
    content: "";
    display: table;
    clear: both;
  }

  p {
    color: white;
  }

  body {
    background-color: black;
  }


  .risk_up_div {
    width: 100px;
    background: red;
    text-align: center;
    margin: 0 auto;
  }

  .risk_up_txt {
    font-size: 25px;
    position: relative;
    top: {{risk_up_posi}};
  }

  .risk_down_div {
    width: 100px;
    background: blue;
    text-align: center;
    margin: 0 auto;
  }

  .risk_down_txt {
    font-size: 25px;
    position: relative;
    top: {{risk_down_posi}};
  }

  .reward_div {
    text-align: center;
    margin: 0 auto;
  }

  .reward_txt {
    font-weight: normal;
    font-size: 40px;
  }

  .certainty_div {
    text-align: center;
    margin: 0 auto;
  }

  .certainty_txt {
    /* font-family: "Times New Roman", Times, serif;
    font-weight: normal;
    font-size: 90px; */
    font-weight: 300;
    font-size: 85px;
    position: relative;
    top: 120px;
  }

  .otree-timer {
    display: none;
  }

</style>
{% endblock %}

choice_practice/templates/choice_practice/DecisionPage.html
{% extends "global/Page.html" %}
{% load otree static %}

{% block title %}
Practice Session
{% endblock %}

{% block content %}

<body onload="setStartTime()">
  {% if display == 0 %}
  <!-- lottery shown on the right hand side -->
  <br>
  <section>
    <article id="option_left">

      <div class="certainty_div">
        <p class = "certainty_txt">{{ certainty }}</p>

      </div>

    </article>

    <article id="option_right">
      <div class="risk_up_div" style="height: {{ risk_up_px }};">
        <p class="risk_up_txt">{{ risk_up }}</p>
      </div>
      <div class="risk_down_div"  style="height: {{ risk_down_px }};">
        <p class="risk_down_txt">{{ risk_down }}</p>
      </div>
      <div class="reward_div">
        <p class="reward_txt">{{ reward }}</p>
      </div>

    </article>
  </section>

  {% else %}
  <!-- lottery shown on the left hand side -->
  <br>
  <section>
    <article id="option_left">
      <div class="risk_up_div" style="height: {{ risk_up_px }};">
        <p class="risk_up_txt">{{ risk_up }}</p>
      </div>
      <div class="risk_down_div"  style="height: {{ risk_down_px }};">
        <p class="risk_down_txt">{{ risk_down }}</p>
      </div>
      <div class="reward_div">
        <p class="reward_txt">{{ reward }}</p>
      </div>

    </article>

    <article id="option_right">

      <div class="certainty_div">
        <p class = "certainty_txt">{{ certainty }}</p>

      </div>

    </article>
  </section>
  {% endif %}

  <div style="font-size: 20px;">
    <br>
    <p>In this trial, you need to decide whether to trade {{certainty}} for a lottery, which has {{risk_down}} percent of chance to win {{reward}}. <br>– If you decide the lottery is more attractive, press the {{lot_key}} key to choose the lottery on the {{lot_key}}. <br>– If you decide to keep the money, press the {{tag_key}} key to choose the monetary amount on the {{tag_key}}.</p>

    <p>[This instruction will not be shown in the actual trials]</p>

  </div>

</body>

<input type="hidden" name="choice" id="id_choice" value='nothing'>
<input type="hidden" name="jsdectime_start" id="id_jsdectime_start" value=0>
<input type="hidden" name="jsdectime_end" id="id_jsdectime_end" value=0>
<!-- <input type="hidden" name="jsdectime" value=0> -->

<!-- <center>(Press left or right arrow)</center> -->

{% endblock %}

{% block scripts %}

<script>
  // document.documentElement.style.cursor = 'none';
  // This is to hide the cursor, work the same as the CSS method.

  function setStartTime() {
    var d = new Date();
    document.getElementById('id_jsdectime_start').value = d.getTime();
  }

  document.addEventListener('keydown', function(event) {
    var d = new Date();

    if(event.keyCode === 37) {
      document.getElementById('id_choice').value = 'left';
      document.getElementById('id_jsdectime_end').value = d.getTime();
      document.getElementById("option_left").style.border = "5px solid white";
      document.getElementById('form').submit();
    }
    if(event.keyCode === 39) {
      document.getElementById('id_choice').value = 'right';
      document.getElementById('id_jsdectime_end').value = d.getTime();
      document.getElementById("option_right").style.border = "5px solid white";
      document.getElementById('form').submit();
    }
  });

</script>

{% endblock %}

{% block styles %}
<style type="text/css">

  .otree-title {
    font-size: 0;
  }

  article {
    float: left;
    width: 50%;
    background-color: black;
    padding: 20px;
    vertical-align: middle;
    height: 450px;
    box-sizing: border-box;
    border: 5px solid transparent;
  }

  /* Clear floats after the columns */
  section:after {
    content: "";
    display: table;
    clear: both;
  }

  p {
    color: white;
  }

  body {
    background-color: black;
  }

  .risk_up_div {
    width: 100px;
    background: red;
    text-align: center;
    margin: 0 auto;
  }

  .risk_up_txt {
    font-size: 25px;
    position: relative;
    top: {{risk_up_posi}};
  }

  .risk_down_div {
    width: 100px;
    background: blue;
    text-align: center;
    margin: 0 auto;
  }

  .risk_down_txt {
    font-size: 25px;
    position: relative;
    top: {{risk_down_posi}};
  }

  .reward_div {
    text-align: center;
    margin: 0 auto;
  }

  .reward_txt {
    font-weight: normal;
    font-size: 40px;
  }

  .certainty_div {
    text-align: center;
    margin: 0 auto;
  }

  .certainty_txt {
    /* font-family: "Times New Roman", Times, serif;
    font-weight: normal;
    font-size: 90px; */
    font-weight: 300;
    font-size: 85px;
    position: relative;
    top: 120px;
  }


</style>
{% endblock %}

choice_practice/templates/choice_practice/FixationPage.html
{% extends "global/Page.html" %}
{% load otree static %}

{% block title %}
Practice Session
{% endblock %}

{% block content %}

<!-- use divs to center the fixation cross -->
<!-- should the background colour be black? -->
<body>
  <!-- <br><br> -->
  <div class="cross">
    <center><p style="font-size: 70px; color: white;"> + </p></center>
  </div>

  <!-- This is just to push away the debug table, should be commented off in actual deploy -->
  <!-- <div style="height: 600px;">
  </div> -->

</body>

{% endblock %}

{% block scripts %}

<!-- <script>
  document.documentElement.style.cursor = 'none';
  // This is to hide the cursor, work the same as the CSS method.

</script> -->

{% endblock %}


{% block app_styles %}

<style type="text/css">

  .otree-title {
    font-size: 0;
  }

  .otree-timer {
    display: none;
  }

  body {
    background: black;
    text-align: center;
  }


  .cross {
    position: relative;
    top: 160px;
  }

</style>

{% endblock %}

choice_practice/templates/choice_practice/Instructions.html
{% extends "global/Page.html" %}
{% load otree static %}

{% block title %}
Part 3: Instructions
{% endblock %}

{% block content %}
<h1 style="font-size: 35px;">Part 3: Instructions</h1>

<body>
  <article>
    <h4>Binary Choices and Your Payment:</h4>
    <p>In the following part, you are asked to make investment decisions based on binary choices. As in Part 2, you are allocated a fund of {{endowment}} (= {{pound}}). In total, 216 trials will be presented to you, each of them represents a trade opportunity. Completing all trials on average takes about 20 to 30 minutes, but you can spend as much time as you want to make decisions.</p>

    <p>As is shown in the figure below, in each trial, you will see a lottery and a monetary amount. You are asked to decide whether to trade the monetary amount from the fund assigned to you for a lottery, of which the reward can potentially make you earn more. If you feel the lottery is more attractive, you can approve this trade by choosing the lottery. Otherwise, If you prefer to keep the money, you can give up the trade opportunity by choosing the monetary amount.</p>

    <p>After completing this section, one random trial will be selected to count. If you chose the lottery in that trial, the monetary amount in the same trial will be deducted from your fund, but you will also receive the outcome of the lottery. On the other hand, if you chose the money, you will keep the entire {{endowment}} and leave without a lottery.</p>

  </article>

  <article class="figure">
    <!-- <h5>Figure 3:</h5> -->
    <br>
    <div class="background">
      <!-- lottery shown on the right hand side -->
      <section>
        <article class="binary">

          <div class="certainty_div">
            <p class = "certainty_txt">{{ certainty }}</p>

          </div>

        </article>

        <article class="binary">
          <div class="risk_up_div" style="height: {{ risk_up_px }};">
            <p class="risk_up_txt">{{ risk_up }}</p>
          </div>
          <div class="risk_down_div"  style="height: {{ risk_down_px }};">
            <p class="risk_down_txt">{{ risk_down }}</p>
          </div>
          <div class="reward_div">
            <p class="reward_txt">{{ reward }}</p>
          </div>

        </article>
      </section>
    </div>
  </article>

  <article class="text">
    <h4>Further Instructions:</h4>

    <p>To make the choice between the lottery and the monetary amount, <b>you can and can only use the left key (&#8592) and the right key (&#8594) on your keyboard,</b> they are located on the bottom-right of a standard keyboard. You can keep your right hand near the arrow keys at all times during this Part, to make it easier.</p>

    <p>To note, the side of display in which each of these two items will appear on the screen will vary from trial to trial. So, in each trial you need to observe their locations and use the correct key to make selection. </p>

    <p>When the choice trials start, we would like to ask you to maximise your browser and concentrate on making investment choices without interruptions. You will have opportunity to take two breaks after the trial 72 and 144.</p>

    <p>Before starting the actual trials, we prepared a short practice session for you to be familiar with the mechanism in this section. This practice session only has six trials, including a rest point in the middle. The practice trials will NOT count for payment.</p>

    <!-- <p>Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test.</p> -->

    <br>
    <button class="btn btn-primary btn-large">
      Start the practice session
    </button>

  </article>

</body>

{% endblock %}

{% block styles %}
<style type="text/css">

  .otree-title {
    font-size: 0;
  }

  h4 {
    text-decoration: underline;
  }

  .figure {
    float: right;
    width: 60%;
    padding: 20px;
    /* height: 300px; */
  }

  .text {
    width: 100%;
  }

  .binary {
    float: left;
    width: 50%;
    background-color: black;
    padding: 20px;
    vertical-align: middle;
    height: 410px;
    box-sizing: border-box;
    border: 5px solid transparent;
  }

  /* Clear floats after the columns */
  section:after {
    content: "";
    display: table;
    clear: both;
  }

  section p {
    color: white;
  }

  .risk_up_div {
    width: 100px;
    background: red;
    text-align: center;
    margin: 0 auto;
  }

  .risk_up_txt {
    font-size: 25px;
    position: relative;
    top: {{risk_up_posi}};
  }

  .risk_down_div {
    width: 100px;
    background: blue;
    text-align: center;
    margin: 0 auto;
  }

  .risk_down_txt {
    font-size: 25px;
    position: relative;
    top: {{risk_down_posi}};
  }

  .reward_div {
    text-align: center;
    margin: 0 auto;
  }

  .reward_txt {
    font-weight: normal;
    font-size: 40px;
  }

  .certainty_div {
    text-align: center;
    margin: 0 auto;
  }

  .certainty_txt {
    /* font-family: "Times New Roman", Times, serif;
    font-weight: normal;
    font-size: 90px; */
    font-weight: 300;
    font-size: 85px;
    position: relative;
    top: 120px;
  }


</style>
{% endblock %}

choice_practice/templates/choice_practice/MyPage.html
{% extends "global/Page.html" %}
{% load otree static %}

{% block title %}
    Page title
{% endblock %}

{% block content %}

    {% next_button %}

{% endblock %}

choice_practice/templates/choice_practice/RestPage.html
{% extends "global/Page.html" %}
{% load otree static %}

{% block title %}
Practice Session
{% endblock %}

{% block content %}

<h3>Have a rest</h3>

<p>You can take a break for up to {{rest_minites}} minutes.</p>

<p>– Trials completed: {{trials_gone}}<br>– Trials left to do: {{trials_left}}</p>

<p>If you feel you are ready to proceed, please click the button below.</p>

<br>
{% next_button %}

<style>
.otree-title {
  font-size: 0;
}

</style>

{% endblock %}

choice_practice/templates/choice_practice/Results.html
{% extends "global/Page.html" %}
{% load otree static %}

{% block title %}
    Page title
{% endblock %}

{% block content %}

    {% next_button %}
{% endblock %}

